name: g_notes
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  awesome_dialog: ^3.1.0
  cloud_firestore: ^4.9.3
  empty_widget: ^0.0.5
  equatable: ^2.0.5
  faker: ^2.1.0
  firebase_auth: ^4.12.1
  firebase_core: ^2.17.0
  firebase_ui_auth: ^1.9.1
  firebase_ui_oauth_apple: ^1.2.13
  firebase_ui_oauth_facebook: ^1.2.13
  firebase_ui_oauth_google: ^1.2.13
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_facebook_auth: ^6.0.2
  flutter_form_builder: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_quill: ^8.1.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  form_builder_validators: ^9.1.0
  gap: ^3.0.1
  get_it: ^7.6.4
  go_router: ^11.1.2
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.5
  introduction_screen: ^3.1.12
  shimmer: ^3.0.0
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/avatars/
    - assets/images/introduction/

  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf
